services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "127.0.0.1:6380:6379"

    volumes:
      - /home/developer/docker/redis/data:/data

    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}

    env_file:
      - /home/developer/docker/redis/.env

    networks:
      - devops

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped

    ports:
      - "127.0.0.1:5540:5540"

    volumes:
      - /home/developer/docker/redisinsight/data:/data

    depends_on:
      - redis

    networks:
      - devops

networks:
  devops:
    external: true
