services:
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped

    ports:
      - "127.0.0.1:8081:8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

    networks:
      - devops

networks:
  devops:
    external: true
