services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped

    ports:
      - "127.0.0.1:9443:9443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/developer/docker/portainer:/data

    security_opt:
      - no-new-privileges:true

    networks:
      - devops

networks:
  devops:
    external: true
