services:
  n8n:
    image: n8nio/n8n:1.54.0
    container_name: n8n
    restart: unless-stopped

    ports:
      - "127.0.0.1:5678:5678"

    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http

      - NODE_ENV=production

      # timezone biar schedule gak ngaco
      - GENERIC_TIMEZONE=Asia/Jakarta

      # security basic
      - N8N_SECURE_COOKIE=false

    volumes:
      - /home/developer/docker/n8n:/home/node/.n8n

    security_opt:
      - no-new-privileges:true

    networks:
      - devops

networks:
  devops:
    external: true
