[gateway]
app-gateway ansible_host=192.168.1.30 ansible_user=gateway

[webservers]
app-space  ansible_host=192.168.1.40 ansible_user=app-space

[dbservers]
app-db ansible_host=192.168.1.50 ansible_user=app-db

[tailscale]
app-tailscale ansible_host=192.168.1.60 ansible_user=app-tailscale

[all_servers:children]
gateway
webservers
dbservers
tailscale
