services:
  nats:
    image: nats:2.10-alpine
    container_name: nats
    restart: unless-stopped

    command: >
      -js
      -m 8222
      -p 4222

    ports:
      - "127.0.0.1:4222:4222"   # client
      - "127.0.0.1:8222:8222"   # monitoring

    volumes:
      - /home/developer/docker/nats/data:/data

    networks:
      - devops

  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    restart: unless-stopped
    depends_on:
      - nats

    entrypoint: /bin/sh
    tty: true

    networks:
      - devops

networks:
  devops:
    external: true
