---
- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: reload postgresql
  systemd:
    name: postgresql
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted
