services:
  minio:
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    container_name: minio
    restart: unless-stopped

    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"

    volumes:
      - /home/developer/docker/minio/data:/data

    env_file:
      - /home/developer/docker/minio/.env

    command: server /data --console-address ":9001"

    networks:
      - devops

    security_opt:
      - no-new-privileges:true

networks:
  devops:
    external: true
