---
- name: Include install tasks
  import_tasks: install.yml
  tags:
    - postgresql
    - postgresql:install

- name: Include config tasks
  import_tasks: config.yml
  tags:
    - postgresql
    - postgresql:config

- name: Include user management tasks
  import_tasks: users.yml
  tags:
    - postgresql
    - postgresql:users

- name: Include backup tasks
  import_tasks: backup.yml
  tags:
    - postgresql
    - postgresql:backup

- name: Include web (Adminer) tasks
  import_tasks: web.yml
  tags:
    - postgresql
    - postgresql:web

- name: Include MOTD tasks
  import_tasks: motd.yml
  tags:
    - postgresql
    - postgresql:motd
